#!/bin/sh
DIR=${0%/*}
BASE="$DIR/../";

if [ $# -eq 2 ]; then
	
	echo ">> Inserting default configuration to market DB";
	psql -h $1 --port=$2 -U market market < ${BASE}Strike/Postgres/init_data.sql 
	echo ">> Configuration has finished";
else
    echo ">> Configure script ocekava 2 argumenty:";
    echo ">> 	./configure_database PSQL_SERVER_ADDRESS PSQL_SERVER_PORT"
    echo ">> "
    echo ">> Priklad:"
    echo ">> 	./configure_database 127.0.0.1 5432"
fi
